"""email_type

Revision ID: 411f752496db
Revises: 4e726ebc8c0e
Create Date: 2022-01-18 21:22:29.242946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '411f752496db'
down_revision = '4e726ebc8c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email', existing_type=mysql.VARCHAR(length=100))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email', existing_type=mysql.VARCHAR(length=100))
    # ### end Alembic commands ###
